package com.ap.steelduxxklantenportaal.enums;

public enum UserPreferenceType {
    SYSTEMNOTIFICATIONORDERSTATUS,
    EMAILNOTIFICATIONORDERSTATUS,
    SYSTEMNOTIFICATIONORDERREQUEST,
    EMAILNOTIFICATIONORDERREQUEST

}
