version: '3.8'
services:
  database:
    image: 'mysql:8.3.0'
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - database
    build: ./backend
    restart: on-failure
    env_file: .env
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.datasource.url": "jdbc:mysql://database:$DB_DOCKER_PORT/$DB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
          "spring.datasource.username": "$DB_USER",
          "spring.datasource.password": "$DB_PASSWORD",
          "flyway.url": "jdbc:mysql://database:$DB_DOCKER_PORT/$DB_DATABASE",
          "flyway.user": "$DB_USER",
          "flyway.password": "$DB_PASSWORD"
        }
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  frontend:
    build: ./frontend
    restart: on-failure
    env_file: .env
    ports:
      - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT
volumes:
  db:
