version: '3.8'

services:
  dev-db:
    image: mysql:8.3.0
    container_name: steelduxx-dev-db
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=steelduxxklantenportaal
    volumes:
      - dev-db:/var/lib/mysql
volumes:
  dev-db:
